### ISSUE TITLE
Empty png file

### ISSUE THREAD

**Issue by retorquere** [tillig/plantuml-in-azdo-wiki#1]
I've set up my project as per https://www.paraesthesia.com/archive/2020/05/11/plantuml-in-azure-devops-wiki/, but with the sample on that same page, I'm getting a zero-byte png file, but no errors.

**Comment by tillig** [comment]
I'm not sure I can troubleshoot with the limited information you've provided.

Here's a way to test:

- Clone this repo.
- Run `npm install` to restore packages.
- Run `npm run watch` to start the watcher.
- Open the `Diagrams/Simple-Diagram.png` and verify it currently shows a transition from `Bob -> Alice`.
- Close that image.
- Edit `Simple-Diagram.puml` so it transitions from `Carl -> Alice` - just change the one name.
- Watch the logs for the script - it should output that it detected a change and is regenerating the image.
- Open the `Diagrams/Simple-Diagram.png` and verify it shows `Carl -> Alice`.

If that diagram is now also a zero-byte png, then I'm not sure what to do. I have this running on a few projects, across several devs using both Mac and Windows, and I haven't seen any issues.

**Comment by retorquere** [comment]
You're right, it works in a straight clone, so the problem must be in my integration of it with my existing project. Thanks!
